problem_1:
	ghc ./problem_1.hs
	./problem_1 problem_1_test.txt

problem_1_solve:
	ghc ./problem_1.hs
	./problem_1 problem_1_full.txt


problem_2:
	ghc ./problem_2.hs
	./problem_2 problem_1_test.txt

problem_2_solve:
	ghc ./problem_2.hs
	./problem_2 problem_1_full.txt
